DROP TABLE ORDERER if exists
CREATE TABLE ORDERER(ID VARCHAR(20) NOT NULL,FIRST_NAME VARCHAR(20) NOT NULL,LAST_NAME VARCHAR(20) NOT NULL, SHIPPING_CODE VARCHAR(20) NOT NULL)
INSERT INTO ORDERER VALUES('100','太郎','田中', '001')
INSERT INTO ORDERER VALUES('201','花子','鈴木', '002')