DROP TABLE PRODUCT if exists
CREATE TABLE PRODUCT(CODE VARCHAR(20) NOT NULL, NAME VARCHAR(20) NOT NULL)
INSERT INTO PRODUCT(CODE,NAME) VALUES('001','鉛筆')
INSERT INTO PRODUCT(CODE,NAME) VALUES('002','万年筆')